# Just setting the name of our action
name: Deploy

on: push

jobs:
  test-and-build:
    name: Test and build project
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        # The default profile contains both rustfmt and clippy.
        run: |
          rustup toolchain install stable --profile default --no-self-update --target ${{ matrix.target }}

      - name: Test code
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose

      - name: Lint code
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --release --target ${{ matrix.target }}

      - name: Build archive
        id: archive-builder
        shell: bash
        run: |
          binary_name="pstate_update"
          dirname="$binary_name-${{ matrix.target }}"
          mkdir "$dirname"
          mv "target/${{ matrix.target }}/release/$binary_name" "$dirname"
          cp "${binary_name}.service" "$dirname"
          cp "config.toml" "$dirname"
          tar -czf "${dirname}.tar.gz" "$dirname"
          echo "ASSET=${dirname}.tar.gz" >> "$GITHUB_OUTPUT"

      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        env:
          ASSET: ${{ steps.archive-builder.outputs.ASSET }}
        with:
          name: binary-${{ matrix.target }}
          path: ${{ env.ASSET }}

  release-binaries:
    name: Upload binaries to GitHub Releases page
    runs-on: ubuntu-lates
    needs: test-and-build
    # Write permission are required to upload build artifact as release.
    permissions:
      contents: write
    # TODO: Possibly a better way to do this?
    if: startsWith(github.ref, 'refs/tags/v')

    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
          - target: x86_64-unknown-linux-gnu

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: binary-${{ matrix.target }}

      - name: Get the release version from the tag
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Rename artifacts
        shell: bash
        run: mv 

      - name: Upload the binaries
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ASSET }}
